# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               DISCOVER Cookbook
tagline:             'Diverse & Inclusive Spaces and Conferences'
description:         "The NumFOCUS DISCOVER Cookbook: Daniel's Fork"
url:                 https://danielclough.github.io
giturl:              https://danielclough.github.io
baseurl:             /DISCOVER-Cookbook
paginate:            5

# Custom vars
version:             0.0.1

github.repo: https://github.com/danielclough/discover-cookbook
